### ISSUE TITLE
Qt tools detection issues on various platforms

### ISSUE THREAD

**Issue by luigino** [projectM-visualizer/projectm#172]
The script has a hardcoded call to qmake, that's qmake-qt5 in this case.

Not sure if there's a variable to be used here or if the script should just look for both first.

**Comment by luigino** [comment]
This does the trick for me:
```
PATH="$PATH:`pkg-config --variable=host_bins Qt5Core`"
```

It would also solve the moc/rcc/uic -qt5 dual check in configure.ac. Should it be included or just kept downstream?

**Comment by revmischa** [comment]
Can I ask... are you using the latest master? That check was removed. Did you autoreconf (autogen.sh)?

**Comment by revmischa** [comment]
I am however having trouble building on OSX, after adding `qmake` to my `PATH`:
```
checking for Qt... Info: creating stash file /var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/.qmake.stash
Cannot find file: tmp.ObOWIEV1.
make: *** [/var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/tmp.KAmeP0zu] Error 2
Cannot find file: tmp.ObOWIEV1.
make: *** [/var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/tmp.KAmeP0zu] Error 2
yes:
    QT_CXXFLAGS= 
    QT_DIR=/Users/cyber/dev/Qt/5.12.1/clang_64/lib
    QT_LIBS= 
    QT_UIC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/uic
    QT_MOC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/moc
    QT_RCC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/rcc
    QT_LRELEASE=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/lrelease
    QT_LUPDATE=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/lupdate
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```

Qt has no end of bullshit when it comes to compiling stuff it seems. I've been trying to get this to work and when it works for one platform, others break. Not sure what the right solution is. But that moc/rcc/uic -qt5 thing was fixed by AX_HAVE_QT, or should have been.

**Comment by luigino** [comment]
> Can I ask... are you using the latest master?

I downloaded a snapshot for good measure and there was no change.

>  That check was removed.

I can still see it here: https://github.com/projectM-visualizer/projectm/blob/master/m4/autoconf-archive/ax_have_qt.m4#L68

> Did you autoreconf (autogen.sh)?

I did run ```autoreconf -fiv```.
Anyway even by adding the search path, the build fails like Fedora here: https://github.com/projectM-visualizer/projectm/issues/138#issuecomment-469018916.

**Comment by revmischa** [comment]
Okay I was referring to "the moc/rcc/uic -qt5 dual check in configure.ac." which is gone now
I really don't know what the answer is... builds on ubuntu but not other places it seems
Was trying this out, not sure if it's any better https://github.com/tsuna/autotroll

**Comment by mrturcot** [comment]
I would just like to note, it's also building fine on Arch Linux / Manjaro along with Ubuntu.

**Comment by revmischa** [comment]
If anyone can help get Qt straightened out on their platform, please send in a PR!

**Comment by luigino** [comment]
ax_have_qt.m4 demands an **entire** Qt5 installation, including linguist tools, which we don't need.

**Comment by sergiomb2** [comment]
As project use qmake 

I need to set %{_libdir}/qt5/bin in the PATH

    export PATH="/usr/lib64/qt5/bin:$PATH"

**Comment by sergiomb2** [comment]
I checked it yesterday  and qt-autools [1]  is updated and IMO correctly configured , but relies only on qmake be in PATH. In Fedora packaging we got one rpm macro %{cmake_kf5} that set qmake in PATH like it showed in previous post , also we got %{_qt5_qmake} that is complete path of qmake ( /usr/lib64/qt5/bin/qmake ) , we got %{qmake_qt5} macro and  %{_qt5_qmake_flags} . Also we got qmake-qt5 locate in /usr/bin.
In resume ax_have_qt.m4 may be improve, for example to check in qmake-qt5 exist but for now we just need add qmake to the PATH manually [2] .

[1]
cat m4/autoconf-archive/ax_have_qt.m4  | grep qmake

[2]

    export PATH="/usr/lib64/qt5/bin:$PATH"

**Comment by revmischa** [comment]
please feel free to extend ax_have_qt.m4. I made a change to it and submitted a PR and they merged it [right away](https://github.com/autoconf-archive/autoconf-archive/pull/186), so you can get your changes upstream too if you feel like it

**Comment by slyholborn** [comment]
Hi! How can i help? I'm afraid i have no coding skills, but i can test stuffs! I run fedora 29 on several PC's

**Comment by sergiomb2** [comment]
> Hi! How can i help? I'm afraid i have no coding skills, but i can test stuffs! I run fedora 29 on several PC's

You have a build on koji [1] that you can test, meanwhile I found a bug in gcc of Fedora (only) in i686 arches ,  I'm waiting for a new build of gcc to test if I can build libprojectM in i686 ...
Anyway will be hard update F29 officially because will be broken dependencies on yum/dnf, apps like clementine depends on shared libraries 2.1 and now we are in 3.1 .


[1]
https://koji.fedoraproject.org/koji/buildinfo?buildID=1230085

**Comment by sergiomb2** [comment]
> please feel free to extend ax_have_qt.m4. I made a change to it and submitted a PR and they merged it [right away](https://github.com/autoconf-archive/autoconf-archive/pull/186), so you can get your changes upstream too if you feel like it

ax_have_qt.m4 of projectM is more updated than https://www.gnu.org/software/autoconf-archive/ , the last commit is very important to have a successful build . 

I just saw that you upstream it [1] , many thanks .

https://github.com/autoconf-archive/autoconf-archive/commit/d3ff0497b247b4150768a5b2d852b388a2e790e6
