### ISSUE TITLE
FPS drops to 0 Consistently! 

### ISSUE THREAD

**Issue by Flingafu** [projectM-visualizer/projectm#338]
Hey so I'm using project M with a pretty beefy system, milkdrop runs just fine, but for whatever reason project m locks up for 1second out of every 3-4. It doesnt matter what visual is playing, or even if its the same one over and over, I can literally watch my GPU dip at every freeze, picture related!
![wth](https://user-images.githubusercontent.com/48436414/79703786-d7b87600-827b-11ea-8b19-e4df6c6c7c32.png)

**Comment by Flingafu** [comment]
I even stopped a bunch of stuff in the background, the dips are the same visually, but just a little more difficult to see on the graph, i hold a rock steady 60FPS then straight to 0 for a bit then back to normal! any help would be much obliged!
![wth2](https://user-images.githubusercontent.com/48436414/79703855-60cfad00-827c-11ea-86a5-6cb3f731128f.png)

**Comment by R0TEAM** [comment]
have the same problem .... but it is not so easy ;)
have 3 windows 10 pro devices ...
Surface Pro 5 - here it runs smooth
an Core2 Quad PC with an AMD HD7870XT GPU - here it runs smoth
and my main workstation, with an 12 Core Xeon CPU and an AMD FirePro w8100 GPU
.. here i have the FPS drop - ot "freeze" problem .. runs a couple of seconds nice .. then a short "freeze" - and it runs again nice
all drivers on all devices up-to-date

**Comment by SirJson** [comment]
Same Problem here running the latest Version of projectM SDL on Windows with a RTX 2070. It also seems to max out around 60 FPS on a 144hz display. The Fullscreen Mode didn't change this unfortunately.

**Comment by SirJson** [comment]
OK I should RTFM, there is a fps setting. Also I don't know why UNLOCKED_FPS is set to 0 by default... it seems to be used for performance testing?

I fixed the problem locally by setting UNLOCKED_FPS to 1, removing the benchmark code(?) and adding a new function on Windows that sets the default fps equal to the current display refresh rate.

Since it now works flawlessly I will sent a PR, but only after I restored the removed parts. I better don't delete code just because I don't understand it 😅

**Comment by milkdropper** [comment]
You are using the SDL version right? I'm not having dropping FPS issues but I can help you get past 60 fps.

The cap is in the hard coded settings in projectM_SDL_main.cpp:
`settings.fps = 60;`

I just set that to 144 on my 144hz and WOW, what an improvement! I'll submit a PR to cap the FPS at the currently focused monitors refresh rate.

**Comment by SirJson** [comment]
I sort of did that, in my "hacked" version I asked Windows what my display refresh rate is. And that version worked really good. Then I was like ok let's make this a PR and I noticed that you can get the same information from SDL. 

So I wrote a version that uses SDL for that information and sets the FPS to that. The code is working, but here is the part where I'm stuck. The stutter bug is still there and no matter what I do I can't get the good version back. 

I diffed the quick and dirty version with the clean one, I disabled text rendering, I added UNLIMITED_FPS back in, I checked my GSync settings and if the app really doesnt enable it (gsu and deleted the same lines like last time I even tried to capture it on RenderDoc. The thing is all I can see is that most milkdrop cause one DrawBuffer call that is uninitalized but even on the good ones I have framedrops every 3-5 seconds.

What I also saw is that the GPU is basically bored with projectM so at this point I'm just guessing. It could be 

a) all those single uninitalized buffer calls are causing issues in the Nvidia driver
b) using the WinAPI to query for screen refresh rate triggered something internal and hidden and that made it work
c) G-Sync is doing it's thing again. A lot of windows app's are also suffering from a smililar issue but the solution so far is to restrict G-Sync to fullscreen mode which I have. I also checked if the SDL application is not sneaky enabling it or something.
d) I noticed that projectM SDL is running single threaded and I'm using a Ryzen 3700+. Since RenderDoc told me that every frame could have been shown at an even higher rate than 144 fps it might have just another weird Agesa bug where the firmware strugles to schedule everything correctly? I would have no proof for that but also wouldn't supprise me...
e) Audio driver bugs? I wonder if the same issue would popup if projectM SDL would also be a audio player and is feeding the data directly.

So I feel like this issue is beyond my abilities without someone who actually knows his way around the projectM source code.

That being said I also had a bad day and lost a bunch of source code by moving my workspace to a new hardrive. I will checkout your version and see if it did the trick cause that would be awesome and would losing my work not as painful :)

**Comment by bazzilic** [comment]
Having the same issue on a beefy Win 10 machine.

**Comment by acecs1989** [comment]
I'm having this issue as well. It freezes in almost a cycle, like a skipping CD. Just a brief stutter every few seconds but it's enough to prevent me form enjoying the otherwise fantastic visualizations.

Sorry to bump the old thread!

**Comment by revmischa** [comment]
One thing you could potentially try is changing this line: https://github.com/projectM-visualizer/projectm/blob/master/src/projectM-sdl/projectM_SDL_main.cpp#L343
See if that makes any difference

**Comment by acecs1989** [comment]
> One thing you could potentially try is changing this line: https://github.com/projectM-visualizer/projectm/blob/master/src/projectM-sdl/projectM_SDL_main.cpp#L343
> See if that makes any difference

Will I need to build from source? At the moment I am just using the main Windows version and I do not see a file that matches with that one. I appreciate the help and prompt response for this recommendation!

**Comment by revmischa** [comment]
Yes you would need to build from source

**Comment by acecs1989** [comment]
> Yes you would need to build from source

Do you happen to have any information to get the ball rolling on that process? I am plenty capable but do not see much documentation out there on how to go about compiling a custom version from source. My goal for this is to be able to get everything running smoothly and then key out the blacks from the visualization and replace it with my webcam for music streaming on youtube through obs. I'm very close to the goal but just have to get over this hurdle! Thank you!!

**Comment by revmischa** [comment]
I'm not at all familiar with building on windows. You can check out BUILDING.md or ask on the discord if someone can document it

**Comment by milkdropper** [comment]
@acecs1989 - can you try running projectM_0.exe, projectM_1.exe, and projectM_-1.exe in https://github.com/milkdropper/projectm/blob/disablevsync/projectM-vSyncTest.zip

I implemented the 3 possible values for the line @revmisha recommended you test changing. Hopefully one will help based on his advice. If it does, that will help us to isolate the problem.

**Comment by SebastianGi** [comment]
Since setting up my new PC i am experiencing the same/a similar issue (Windows 10), every few seconds theres a short freeze for about half a second. 
I tried the files in the link from the last comment and i am experiencing the issue with all 3 executables.
If you need any additional infos or want me to try to change something (i could do changes and build) i'd be glad to help.

**Comment by SebastianGi** [comment]
I thought i might as well share some more infos that might help you narrow the issue down:

- I am using a GSync compatible 144hz Screen, but the issue appears wether GSync is enabled or not.
- My GPU is an RTX 3080
- In the Task Manager im seeing spikes similar to what Flingafu posted.
- The Issue only started appearing once i reinstalled Windows 20H2 after getting a new B550 Motherboard together with an AMD Ryzen 7 5800X
- I have tried removing different devices plugged in to the pc, for example my audio interface or the Wifi Antenna, as i thought that maybe those are causing some spikes, but this did not fix the issue either

**Comment by goosewobbler** [comment]
I *think* I managed to fix this with an update to the project dependencies brought in with NuGet.  I now have a working build with no jerking after updating:

glm @ `0.9.9.400` => `0.9.9.800` (needed adding)
sdl2.nuget @ `2.0.9` => `2.0.14`
sdl2.nuget.redist @ `2.0.9` => `2.0.14`

I still get some very low frame rates but these are consistent and seem to be dependent on the preset.

**Comment by SebastianGi** [comment]
I just built your branch on my machine, and the freezes i was experiencing on my end have been fixed by this.

**Comment by milkdropper** [comment]
This is great news! Can you submit a PR?
Are you sure adding glm via nuget was required? I thought it was bundled in with the source.

**Comment by goosewobbler** [comment]
Already did, can continue the discussion there.
https://github.com/projectM-visualizer/projectm/pull/492

**Comment by chaosophy** [comment]
Nice find on the fix!

Was an annoying bug, also can confirm that making your changes looks to have fixed it.

**Comment by goosewobbler** [comment]
It was super annoying indeed.  Was just lucky that I was messing around with NuGet as part of looking deeper at this and noticed these were out of date.  I probably wouldn't have got too far anyway after picking the low hanging fruit but in my experience updating versions of things is the first port of call when dealing with potential thorny issues.

Tried this without the glm and it seems to work just as well. Would appreciate if some other people could test it again...

**Comment by goosewobbler** [comment]
Merged, woohoo.  Thanks @revmischa.

**Comment by kblaschke** [comment]
Closing as fixed.
