### ISSUE TITLE
Hitches every few seconds on Windows 10, 5950x/3090

### ISSUE THREAD

**Issue by JaredBanyard** [projectM-visualizer/projectm#531]
The downloaded and steam versions hitch every few seconds when running on my machine.

Using latest version from Steam.

**Comment by chaosophy** [comment]
I believe this issue was fixed a while back and the fix is in the latest master branch build but there hasn't been an actual release pushed out in the meantime.
No idea when/if the next release is planned for.

**Comment by milkdropper** [comment]
Now is a good time. I'll push an update tonight or tomorrow at the latest.

**Comment by JaredBanyard** [comment]
Awesome! Really looking forward to it!

**Comment by JaredBanyard** [comment]
@milkdropper Is the release somewhere I'm not seeing, sorry in advance for the ping!

**Comment by JaredBanyard** [comment]
@milkdropper Still having issues? What seems to be the problem?

**Comment by kblaschke** [comment]
@milkdropper If I can support with using CMake, just drop me a note. Since it's all-new, any developer feedback on the new build system is highly appreciated!

**Comment by cristos666** [comment]
Tested the latest build artifacts and still having stutters on an AMD Ryzen 5 3600 and RX 580.

**Comment by kblaschke** [comment]
So far, all reported issues happened on Ryzen-based system as far as people gave hardware specifics.

@JaredBanyard and @milkdropper - you also have these hitches on Ryzen CPUs? If so, then this could be the same issue many Ryzen-based gamers experience with stuttering for a long time now, which would mean from projectM's side there's nothing we could do.

**Comment by aiac** [comment]
Same problem for me. Ryzen 5900x / RTX 3080. No matter what resolution or preset. No spikes on CPU usage. FPS counter shows 60-64 fps and when stutter it shows 10-20 and the frame freezes like that for couple ms

**Comment by BuckleBean** [comment]
Sam problem here. Nvidia 1080ti. 7700k @ 5ghz, 32GB RAM, Win11. Has been doing this for what feels like forever. Seeing these comments started Aug, 2021. That could be around when I noticed. Not sure.
